import type { NextPage } from 'next'
import Head from 'next/head'
import { Button, styled, Typography } from '@mui/joy'
import Link from 'next/link';

const MainContainer = styled('main')`
  margin: 8rem;
`

const Home: NextPage = () => {

  return (<>
    <Head>
      <title>CTAP Demo Landing</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <MainContainer>
      <Typography level={'display1'}>Test</Typography>
      <Link href={'/auth'} passHref legacyBehavior>
        <Button size={'lg'} component={'a'}>Log In!</Button>
      </Link>
    </MainContainer>
  </>)
}

export default Home
