import type { NextPage } from 'next'
import Head from 'next/head'
import { Button, Container, Typography } from '@mui/joy'
import Link from 'next/link';
import Toolbar from '../components/Toolbar';

const Home: NextPage = () => {

  return (<>
    <Head>
      <title>WebAuthn Landing</title>
      <meta name="description" content="Generated by create next app" />
    </Head>

    <Toolbar />
    <Container maxWidth={'md'} sx={{ textAlign: 'center' }}>
      <Typography level={'display2'} mt={16} mb={2}>Taking <span style={{ color: 'var(--joy-palette-primary-400)' }}>Web Authen</span>tication to the next level</Typography>
      <Typography mb={2}>
        WebAuthn is the future of web authentication: single-click sign on, strong
      </Typography>
      <Link href={'/auth'} passHref legacyBehavior>
        <Button size={'lg'} component={'a'}>Give it a try!</Button>
      </Link>
    </Container>
  </>)
}

export default Home
